apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "vault-exporter.fullname" . }}
  labels:
    app: {{ template "vault-exporter.name" . }}
    chart: {{ template "vault-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vault-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vault-exporter.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VAULT_ADDR
              value: "https://vault-release-vault"
            - name: VAULT_TLS_SERVER_NAME
              value: "vault.halfpipe-test.io"
            - name: VAULT_TOKEN
              value: "57be2567-310a-5497-b668-e893fe1f1b4a"
            - name: VAULT_SKIP_VERIFY
              value: "true"
          ports:
            - name: prometheus
              containerPort: 9410
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: prometheus
          readinessProbe:
            httpGet:
              path: /
              port: prometheus
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
