# Default values for vault-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/halfpipe-io/vault-exporter
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9410
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/probe_path: "/metrics"
    prometheus.io/port: "9410"
    prometheus.io/scrape: "true"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
